name = "portfolio-v2"
main = "./.next/standalone/server.js"
compatibility_date = "2023-05-07"

[build]
command = "npm run build"

[site]
bucket = "./.next/static"

[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "production"